name: Dialyzer
description: Run Dialyzer, maintaining a cache of the PLT files
inputs:
  cmd-line:
    description: Additional command line options to pass to `mix dialyzer`
    default: ""
  github-actions-formatting:
    description: Enables dialyxir's "Github Actions message format" command line parameters
    default: true
  working-directory:
    description: Directory to change to before running Dialyzer
    default: "."
  use-fallback-cache-keys:
    description: Whether or not to use the fallback cache keys, which look for inexact matches.
    default: "true"
  cache-key-version:
    description: a string to change the cache key if the old cached value is stale
    default: ""
runs:
  using: "node20"
  main: "dist/main/index.js"
