name: Dialyzer
description: Run Dialyzer, maintaining a cache of the PLT files
inputs:
  cmd-line:
    description: Additional command line options to pass to `mix dialyzer`
    default: ""
runs:
  using: "node12"
  main: "dist/main/index.js"
