name: Deploy To Environment
description: Deploy a zip to lambda
inputs:
  role-to-assume:
    description: IAM role
    required: true
  aws-region:
    description: AWS region to use
    required: false
    default: us-east-1
  lambda-function:
    description: Lambda function name
    required: true
  slack-webhook-url:
    description: Slack URL to post to
    required: true
  path-to-zip:
    description: Path to files
    required: false
    default: '.'
  zip-flags:
    description: Files to zip
    required: false
    default: '-r'
runs:
  using: 'composite'
  steps:
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # 6.2.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true
    - name: Package the Lambda function
      shell: bash
      run: |
        zip ${INPUTS_ZIP_FLAGS} function.zip ${INPUTS_PATH_TO_ZIP}
      env:
        INPUTS_ZIP_FLAGS: ${{ inputs.zip-flags }}
        INPUTS_PATH_TO_ZIP: ${{ inputs.path-to-zip }}
    - name: Deploy to AWS Lambda
      shell: bash
      run: |
        aws lambda update-function-code \
          --function-name ${INPUTS_LAMBDA_FUNCTION} \
          --zip-file fileb://function.zip
      env:
        INPUTS_LAMBDA_FUNCTION: ${{ inputs.lambda-function }}
    - uses: mbta/actions/notify-slack-deploy@v1
      if: ${{ !cancelled() }}
      with:
        webhook-url: ${{ inputs.slack-webhook-url }}
        job-status: ${{ job.status }}
