name: Build/push
description: Build a Docker image and push to ECR
inputs:
  role-to-assume:
    description: IAM role
    required: true
  aws-region:
    description: AWS region to use
    required: true
    default: us-east-1
  docker-repo:
    description: ECR Docker repo to push to
    required: true
  dockerfile-path:
    description: Path to the repo's Dockerfile
    required: false
    default: '.'
  docker-additional-args:
    description: Additional arguments to pass to call to docker
    required: false
    default: ''
  docker-additional-tags:
    description: Additional tags for the image, separated by spaces
    required: false
    default: ''
outputs:
  docker-tag:
    description: Docker Tag
    value: ${{ steps.docker.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - run: echo "tag=${{ inputs.docker-repo }}:git-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      id: docker
      shell: bash
    - run: >
        docker build
        ${{ inputs.docker-additional-args }}
        --pull -t ${{ steps.docker.outputs.tag }} ${{ inputs.dockerfile-path }}
      shell: bash
    - run: >
        aws ecr get-login-password --region ${{ inputs.aws-region }}
        | docker login --username AWS --password-stdin ${{ inputs.docker-repo }}
      shell: bash
    - run: docker push ${{ steps.docker.outputs.tag }}
      shell: bash
    - run: >
        docker_additional_tags=(${{ inputs.docker-additional-tags }});
        for tag in ${docker_additional_tags[@]}; do
          docker tag ${{ steps.docker.outputs.tag }} ${{ inputs.docker-repo }}:$tag
          docker push ${{ inputs.docker-repo }}:$tag
        done
      shell: bash
      if: ${{ inputs.docker-additional-tags != '' }}
