name: Build/push
description: Build a Docker image and push to ECR
inputs:
  aws-access-key-id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws-secret-access-key:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  aws-region:
    description: AWS region to use
    required: true
    default: us-east-1
  docker-repo:
    description: ECR Docker repo to push to
    required: true
  dockerfile-path:
    description: Path to the repo's Dockerfile
    required: false
    default: '.'
  docker-additional-args:
    description: Additional arguments to pass to call to docker
    required: false
    default: ''
  docker-additional-tags:
    description: Additional tags for the image, separated by spaces
    required: false
    default: ''
outputs:
  docker-tag:
    description: Docker Tag
    value: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
runs:
  using: composite
  steps:
    - name: Login to AWS ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.docker-repo }}
        username: ${{ secrets.aws-access-key-id }}
        password: ${{ secrets.aws-secret-access-key }}
    - run: >
        for tag in ${{ inputs.docker-additional-tags }}; do
          echo "type=raw,priority=900,value=${tag},enable=true" >> tags.txt
        done
        echo "::set-output name=tags::$(cat tags.txt)"
      shell: bash
      id: more-tags
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.docker-repo }}
        tags: |
          type=sha,priority=1000,prefix=git-
          ${{ steps.more-tags.outputs.tags )}}

    - run: >
        docker build
        ${{ inputs.docker-additional-args }}
        --pull -t ${{ steps.meta.outputs.tags }} ${{ inputs.dockerfile-path }}
      shell: bash
    - run: docker push ${{ steps.meta.outputs.tags }}
      shell: bash
