name: Build/push
description: Build a Docker image and push to ECR
inputs:
  role-to-assume:
    description: IAM role
    required: true
  aws-region:
    description: AWS region to use
    required: true
    default: us-east-1
  docker-repo:
    description: ECR Docker repo to push to
    required: true
  dockerfile-path:
    description: Path to the repo's Dockerfile
    required: false
    default: '.'
  docker-additional-args:
    description: Additional arguments to pass to call to docker
    required: false
    default: ''
  docker-additional-tags:
    description: Additional tags for the image, separated by spaces
    required: false
    default: ''
outputs:
  docker-tag:
    description: Docker Tag
    value: ${{ steps.docker.outputs.tag }}
  docker-tag-suffix:
    description: Docker Tag Suffix (the part after the :)
    value: ${{ steps.docker.outputs.tag-suffix }}
runs:
  using: composite
  steps:
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true
    - run: |
        short_sha=$(git rev-parse --short HEAD)
        echo "tag=${INPUTS_DOCKER_REPO}:git-${short_sha}" >> $GITHUB_OUTPUT
        echo "tag-suffix=git-${short_sha}" >> $GITHUB_OUTPUT
      id: docker
      shell: bash
      env:
        INPUTS_DOCKER_REPO: ${{ inputs.docker-repo }}
    - run: >
        docker build
        ${INPUTS_DOCKER_ADDITIONAL_ARGS}
        --pull -t ${STEPS_DOCKER_OUTPUTS_TAG} ${INPUTS_DOCKERFILE_PATH}
      shell: bash
      env:
        INPUTS_DOCKER_ADDITIONAL_ARGS: ${{ inputs.docker-additional-args }}
        STEPS_DOCKER_OUTPUTS_TAG: ${{ steps.docker.outputs.tag }}
        INPUTS_DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
    - run: >
        aws ecr get-login-password --region ${INPUTS_AWS_REGION}
        | docker login --username AWS --password-stdin ${INPUTS_DOCKER_REPO}
      shell: bash
      env:
        INPUTS_AWS_REGION: ${{ inputs.aws-region }}
        INPUTS_DOCKER_REPO: ${{ inputs.docker-repo }}
    - run: docker push ${STEPS_DOCKER_OUTPUTS_TAG}
      shell: bash
      env:
        STEPS_DOCKER_OUTPUTS_TAG: ${{ steps.docker.outputs.tag }}
    - run: >
        docker_additional_tags=(${INPUTS_DOCKER_ADDITIONAL_TAGS});
        for tag in ${docker_additional_tags[@]}; do
          docker tag ${STEPS_DOCKER_OUTPUTS_TAG} ${INPUTS_DOCKER_REPO}:$tag
          docker push ${INPUTS_DOCKER_REPO}:$tag
        done
      shell: bash
      if: ${{ inputs.docker-additional-tags != '' }}
      env:
        INPUTS_DOCKER_ADDITIONAL_TAGS: ${{ inputs.docker-additional-tags }}
        STEPS_DOCKER_OUTPUTS_TAG: ${{ steps.docker.outputs.tag }}
        INPUTS_DOCKER_REPO: ${{ inputs.docker-repo }}
