name: ElasticBeanstalk ECR Dockerrun.aws.json
description: Build an ElasticBeanstalk Dockerrun.aws.json based on an AWS ECR tag
inputs:
  docker-tag:
    required: true
    description: Docker tag to use in the deployment
  port:
    description: The port to publish (should be exposed by the Dockerfile)
    default: 4000
outputs:
  deployment-package:
    description: Path to the deployment .zip file
    value: ${{ steps.build.outputs.package }}
runs:
  using: composite
  steps:
    - shell: bash
      id: build
      run: |
        echo "package=$(
            mktemp -d $RUNNER_TEMP/package-XXXXXX
          )/${{ github.sha }}.zip" >> $GITHUB_OUTPUT
        echo "dir=$(mktemp -d $RUNNER_TEMP/deploy-XXXXXX)" >> $GITHUB_OUTPUT
    - shell: bash
      run: |
        test -d rel/.ebextensions && cp -r rel/.ebextensions ${STEPS_BUILD_OUTPUTS_DIR}
        pushd ${STEPS_BUILD_OUTPUTS_DIR} > /dev/null
        cat <<EOF > Dockerrun.aws.json
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "${INPUTS_DOCKER_TAG}",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "${INPUTS_PORT}"
            }
          ]
        }
        EOF
        zip -r ${STEPS_BUILD_OUTPUTS_PACKAGE} .
        popd > /dev/null
        rm -rf ${STEPS_BUILD_OUTPUTS_DIR}
        echo Created build package: ${STEPS_BUILD_OUTPUTS_PACKAGE}
      env:
        STEPS_BUILD_OUTPUTS_DIR: ${{ steps.build.outputs.dir }}
        INPUTS_DOCKER_TAG: ${{ inputs.docker-tag }}
        INPUTS_PORT: ${{ inputs.port }}
        STEPS_BUILD_OUTPUTS_PACKAGE: ${{ steps.build.outputs.package }}
