name: CI

on:  # Triggers the workflow on push or pull request events
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  yaml:
    name: Validate YAML actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - run: yamllint -f parsable .

  chmod:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: shellcheck
        run: find . -name '*.sh' | xargs shellcheck -S warning
      - name: Ensure .sh files have chmod +x
        run: find . -name '*.sh' \! -executable | (! grep .)

  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          # pedantic persona gives too many noisy template-injection problems to manually fix
          persona: regular
          advanced-security: false
          annotations: true
